/*
 * vistaApplet.java
 *
 * Created on 10 de diciembre de 2009, 22:56
 */
package ecuaciongeneral;

import java.awt.BorderLayout;
import java.awt.Graphics2D;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author  Frank
 */
public class vistaApplet extends javax.swing.JApplet {

    private Graphics2D g;
    EcuacionGeneral ecuacion;

    /** Initializes the applet vistaApplet */
    public void init() {

        try {
            ecuacion = new EcuacionGeneral(150, 180, 220, 130);
        } catch (Exception ex) {
            Logger.getLogger(vistaApplet.class.getName()).log(Level.SEVERE, null, ex);
        }
        repaint();
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                    setSize(450, 400);//establece el tamaño del applet
                    ecuacion.setSize(450, 400);//establece el tamaño del panel en el que voy a dibujar
                    contenedor.setSize(450, 400);//establece el tamaño del contenedor en el que voy a add
                    contenedor.setLayout(new BorderLayout(10, 5));//establece el administrador de diseño para ese panel
                    contenedor.add(ecuacion, BorderLayout.CENTER);

                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();

        contenedor.setBackground(new java.awt.Color(255, 255, 255));
        contenedor.setPreferredSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedor;
    // End of variables declaration//GEN-END:variables
}
